###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
# See https://wiki.hyprland.org/Configuring/Binds/
$mainMod = SUPER 
$rofiPath = $HOME/.config/rofi

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, exec, $rofiPath/launcher.sh
bind = $mainMod, O, exec, $rofiPath/powermenu.sh

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, Ampersand, workspace, 1
bind = $mainMod, Eacute, workspace, 2
bind = $mainMod, Quotedbl, workspace, 3
bind = $mainMod, Apostrophe, workspace, 4
bind = $mainMod, Parenleft, workspace, 5
bind = $mainMod, Minus, workspace, 6
bind = $mainMod, Egrave, workspace, 7
bind = $mainMod, Underscore, workspace, 8
bind = $mainMod, Ccedilla, workspace, 9
bind = $mainMod, Agrave, workspace, 10

bind = $mainMod SHIFT, Ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, Eacute, movetoworkspace, 2
bind = $mainMod SHIFT, Quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, Apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, Parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, Minus, movetoworkspace, 6
bind = $mainMod SHIFT, Egrave, movetoworkspace, 7
bind = $mainMod SHIFT, Underscore, movetoworkspace, 8
bind = $mainMod SHIFT, Ccedilla, movetoworkspace, 9
bind = $mainMod SHIFT, Agrave, movetoworkspace, 10

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
