#############
### STYLE ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(83c092ff) rgba(83c092ff)
    col.inactive_border = rgba(53605cff) rgba(53605cff)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 5
    shadow {
        enabled = no
    }
    blur {
        enabled = no
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true
	
    bezier = wind, 0.3, 0.0, 0.3, 1.0
    bezier = windIn, 0.3, 0.0, 0.3, 1.0
    bezier = windOut, 0.3, 0.0, 0.3, 1.0
    bezier = liner, 1, 1, 1, 1

    animation = windows, 1, 2, wind, popin
    animation = windowsIn, 1, 2, windIn, popin
    animation = windowsOut, 1, 2, windOut, popin
    animation = windowsMove, 1, 2, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 2, default
    animation = workspaces, 1, 2, wind
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true     
    preserve_split = true
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}
